# Generated by Django 5.2.3 on 2025-06-16 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_event_event_id_alter_event_title"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("user", "event")},
        ),
        migrations.AddField(
            model_name="reservation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservation_id",
        ),
    ]
