# Generated by Django 5.2.3 on 2025-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=20)),
                ("date_and_time", models.DateTimeField()),
                ("ticket_price", models.IntegerField()),
                ("available_tickets", models.IntegerField()),
                ("age", models.IntegerField()),
            ],
        ),
    ]
