# Generated by Django 5.2.3 on 2025-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="age",
            field=models.IntegerField(
                choices=[("everybody", 10), ("teen", 14), ("mature", 18)],
                default="everybody",
            ),
        ),
    ]
