# Generated by Django 5.2.3 on 2025-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="age",
            field=models.IntegerField(
                choices=[(10, 10), (14, 14), (18, 18)], default="everybody"
            ),
        ),
    ]
