# Generated by Django 5.2.3 on 2025-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="age",
            field=models.IntegerField(
                choices=[(0, "everybody"), (14, "teens"), (18, "adults")],
                default="everybody",
            ),
        ),
    ]
